name: CPU

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        model: 
          - d2q9_weird
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Init overlay
      shell: bash
      run: ./update.sh --submodules
    - name: Install dependencies
      uses: CFD-GO/TCLB/.github/actions/install@master
      with:
        rinside: true
    - name: Configure
      uses: CFD-GO/TCLB/.github/actions/configure@master
      with:
        gpu: false
        paranoid: true
    - name: Compile
      uses: CFD-GO/TCLB/.github/actions/compile@master
      with:
        model: ${{ matrix.model }}
    - name: Run tests
      uses: CFD-GO/TCLB/.github/actions/test@master
      with:
        model: ${{ matrix.model }}
